@WebApi_HostAddress=https://localhost:5002



GET https://localhost:5002/api/contacts
Accept: application/json

###


GET {{WebApi_HostAddress}}/api/contacts/B9C5842A-FA13-4A1A-97EC-8B4C2420432E
Accept: application/json

###


POST https://localhost:5002/api/contacts
Content-Type: application/json

{

  "firstName": "Karolina",
  "lastName" : "Pruszkowska",
  "email": "Karo@wsei.edu.pl",
  "phone": "48123456789",
  "gender": "Female"
}

###


POST https://localhost:5002/api/contacts/4A5D8B43-0099-4CB6-A57E-393F2C185E86/notes
Content-Type: application/json

{
  "content": "To jest przykładowa notatka 1"
}

###


GET {{WebApi_HostAddress}}/api/contacts/3cce91f6-3865-4c3a-a462-dacc72297bd1/notes
Content-Type: application/json

###


DELETE {{WebApi_HostAddress}}/api/contacts/4A5D8B43-0099-4CB6-A57E-393F2C185E86
Content-Type: application/json

###
